added new extra checks

diff --git a/git-custom-hooks b/git-custom-hooks
--- a/git-custom-hooks
+++ b/git-custom-hooks
@@ -93,8 +93,8 @@ custom_git() {
 	run_pre_hook "$@"
 
 	#if exist code from hook is 0 then we can continue to execute git command
-	hook_exit_code="$?"
-	if [ $hook_exit_code -eq '0' ]; then
+	exit_code="$?"
+	if [ $exit_code -eq '0' ]; then
 		\git "$@"
 	fi
 
@@ -182,45 +182,69 @@ publish()
 	printf "\n$BCyan--- Commit changes ---$NC\n"
 	
 	git commit  --no-edit -am "$message"
-	hook_exit_code="$?"
-	if [ $hook_exit_code -gt "1" ]; then
-		printf " ${BRed} Aborted!\n ${NC}"; return;
+	exit_code="$?"
+	if [ $exit_code -gt "1" ]; then
+		printf " ${BRed} Aborted!\n ${NC}"; 
+        return 1;
 	fi
 	
 	
 	printf "\n$BCyan--- Checkout branch $br_to_pub ---$NC\n"
 	git checkout "$br_to_pub"
+
+    ck_branch=$(git branch | sed -n -e 's/\* //p')
+	ck_branch=$(echo "$ck_branch" | sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g')
+
+	if [ "$ck_branch" != "$br_to_pub" ]; then
+		printf " ${BRed} Aborted!\n ${NC}"; 
+        return 1;
+	fi
+	
 	
     printf "\n$BCyan--- Fetch changes from remote ---$NC\n"
     git fetch
 
+    exit_code="$?"
+	if [ $exit_code -gt "0" ]; then
+		printf " ${BRed} Aborted!\n ${NC}"; 
+        return 1;
+	fi
+	
+
     printf "\n$BCyan--- Reset to origin ---$NC\n"
     git reset --hard origin/$br_to_pub
 	
-	hook_exit_code="$?"
-	if [ $hook_exit_code -gt "0" ]; then
-		printf " ${BRed} Aborted!\n ${NC}"; return;
+	exit_code="$?"
+	if [ $exit_code -gt "0" ]; then
+		printf " ${BRed} Aborted!\n ${NC}"; 
+        return 1;
 	fi
 	
 	printf "\n$BCyan--- Merge $cur_branch into $br_to_pub ---$NC\n"
 	git merge "$cur_branch"
 	
-	hook_exit_code="$?"
-	if [ $hook_exit_code -gt "0" ]; then
-		printf " ${BRed} Aborted!\n ${NC}"; return;
+	exit_code="$?"
+	if [ $exit_code -gt "0" ]; then
+#		printf " ${BRed} Aborted!\n ${NC}"; 
+        
+        printf "\n$BCyan--- Checkout branch $cur_branch ---$NC\n"
+        git checkout "$cur_branch"
+        return 1;
 	fi
 	
 	printf "\n$BCyan--- Push changes into $br_to_pub ---$NC\n"
 	git push
 	
-	hook_exit_code="$?"
-	if [ $hook_exit_code -gt "0" ]; then
-		printf " ${BRed} Aborted!\n ${NC}"; return;
+	exit_code="$?"
+	if [ $exit_code -gt "0" ]; then
+		printf " ${BRed} Aborted!\n ${NC}"; 
+        return 1;
 	fi
 	
 	printf "\n$BCyan--- Checkout branch $cur_branch ---$NC\n"
 	git checkout "$cur_branch"
 }   
+   
 
 alias git=custom_git
 alias cd=reminder_cd
