fix bug when publish on the same branch

diff --git a/git-custom-hooks b/git-custom-hooks
--- a/git-custom-hooks
+++ b/git-custom-hooks
@@ -187,6 +187,7 @@ publish()
 	cur_branch=$(git branch | sed -n -e 's/\* //p')
 	cur_branch=$(echo "$cur_branch" | sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g')
 
+#   Compose the message
      if [[ ${cur_branch} != [0-9]* ]]; then
 	    if [[ ${*:2} == [0-9]* ]]; then
 	        message="#${*:2}"
@@ -197,21 +198,39 @@ publish()
 	    message="#${cur_branch} ${*:2}"
 	fi
 
+    ######################  COMMIT  ###########################
+
 	printf "\n$BCyan--- Commit changes ---$NC\n"
 
 	git commit  --no-edit -am "$message"
 	exit_code="$?"
-
 	if [ $exit_code -gt "1" ]; then
         return 1;
 	fi
 
-	if [ $cur_branch == $br_to_pub ]; then
+    ###########################################################
+
+	pb_on_same_branch=[ $cur_branch == $br_to_pub ];
+
+#    if we publish on the same branch we dont need to reset the code, just pull the changes
+	if $pb_on_same_branch; then
+
+        ######################  PULL  ###########################
 
         printf "\n$BCyan--- Pull changes from repo ---$NC\n"
         git pull
 
+        exit_code="$?"
+        if [ $exit_code -gt "0" ]; then
+            if [ $exit_code -eq "1" ]; then
+                printf " ${BRed} Aborted!\n ${NC}";
+            fi
+            return 1;
+        fi
+
 	else
+
+        ######################  CHECKOUT  ###########################
 
         printf "\n$BCyan--- Checkout branch $br_to_pub ---$NC\n"
         git checkout "$br_to_pub"
@@ -224,6 +243,8 @@ publish()
             return 1;
         fi
 
+        ######################  FETCH  ###########################
+
         printf "\n$BCyan--- Fetch changes from remote ---$NC\n"
         git fetch
 
@@ -235,6 +256,7 @@ publish()
             return 1;
         fi
 
+        ######################  RESET  ###########################
 
         printf "\n$BCyan--- Reset to origin ---$NC\n"
         git reset --hard origin/$br_to_pub
@@ -246,6 +268,8 @@ publish()
             fi
             return 1;
         fi
+
+        ######################  MERGE  ###########################
 
         printf "\n$BCyan--- Merge $cur_branch into $br_to_pub ---$NC\n"
         git merge "$cur_branch"
@@ -260,7 +284,11 @@ publish()
             git checkout "$cur_branch"
             return 1;
         fi
+        ##########################################################
+
     fi
+
+    ######################   PUSH   ###########################
 
 	printf "\n$BCyan--- Push changes into $br_to_pub ---$NC\n"
 	git push origin $br_to_pub
@@ -273,8 +301,13 @@ publish()
         return 1;
 	fi
 
-	printf "\n$BCyan--- Checkout branch $cur_branch ---$NC\n"
-	git checkout "$cur_branch"
+    ######################   CHECKOUT   ######################
+
+    #if we dont publish on the same branch, go back to branch where you was before publish
+    if [ !$pb_on_same_branch ]; then
+        printf "\n$BCyan--- Checkout branch $cur_branch ---$NC\n"
+        git checkout "$cur_branch"
+	fi
 }
 
 
